SM:
  - 1.0039777714049951
  - -0.012134297290053364
  - 0.0017696978413674295
  - 0.0063757666414606777
  - 1.0049351593638329
  - 0.0023129106267775908
  - -0.0043771973342752379
  - -0.0033341430160677889
  - 1.0018548082011509
bias:
  - 0.21001243642936263
  - 0.64652075794650476
  - -0.029920033721250093